### ISSUE TITLE
最后一步出错是怎么回事python test_stage_2.py --config ./configs/test_stage_2.yaml

### ISSUE THREAD

**Issue by yan616810** [TMElyralab/MusePose#31]
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.11.5 (you have 3.11.7)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Width: 512
Height: 512
Length: 300
Slice: 48
Overlap: 4
Classifier free guidance: 3.5
DDIM sampling steps : 20
skip 1
Traceback (most recent call last):
  File "F:\kuaisufangwen\Desktop\MusePose\test_stage_2.py", line 238, in <module>
    main()
  File "F:\kuaisufangwen\Desktop\MusePose\test_stage_2.py", line 78, in main
    ).to("cuda", dtype=weight_dtype)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\kuaisufangwen\Desktop\ylad\Lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\kuaisufangwen\Desktop\ylad\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "F:\kuaisufangwen\Desktop\ylad\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "F:\kuaisufangwen\Desktop\ylad\Lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "F:\kuaisufangwen\Desktop\ylad\Lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\kuaisufangwen\Desktop\ylad\Lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by nitinmukesh** [comment]
Refer the video posted here [https://github.com/TMElyralab/MusePose/issues/8](url)
