### ISSUE TITLE
setup issue on mac 

### ISSUE THREAD

**Issue by jnakrani** [TMElyralab/MusePose#62]

**Comment by seinfinity** [comment]
> Hello @TZYSJTU
> 
> I am experiencing issues running pose_align.py from the MusePose repository on my MacBook M3 Max. Despite following the setup instructions in the README and installing all the required libraries and dependencies, I encounter errors when executing the script.
> 
> Environment:
> 
> * OS: macOS
> * Device: MacBook M3 Max
> * Python Environment: Anaconda torch-metal profile
> * Python Version: 3.10
> * MusePose Version: 1.3.1
> * Platform: macOS-14.5-arm64-arm-64bit
> 
> I executed the following command:
> 
> ```shell
> python pose_align.py --imgfn_refer ./assets/images/ref.png --vidfn ./assets/videos/dance.mp4
> ```
> 
> ###Observation###
> 
> * Multiple warnings about missing modules despite it being installed correctly:
> 
> ```shell
> warnings.warn('Fail to import `MultiScaleDeformableAttention` from `mmcv.ops.multi_scale_deform_attn` ')
> warnings.warn('The module `mmpose` is not installed. The package will have limited functionality.')
> warnings.warn('The module `mmdet` is not installed. The package will have limited functionality.')
> ```
> 
> * The script terminates with a `NameError` indicating that `init_detector` is not defined:
> 
> ```shell
> Traceback (most recent call last):
>   File "/Users/jaydip/Documents/BCS/ML/MusePose/pose_align.py", line 556, in <module>
>     main()
>   File "/Users/jaydip/Documents/BCS/ML/MusePose/pose_align.py", line 551, in main
>     run_align_video_with_filterPose.translate_smooth(args)
>   File "/Users/jaydip/Documents/BCS/ML/MusePose/pose_align.py", line 270, in run_align_video_with_filterPose.translate_smooth
>     detector = DWPoseDetector(
>   File "/Users/jaydip/Documents/BCS/ML/MusePose/pose/script/dwpose.py", line 74, in __init__
>     self.pose_estimation = Wholebody(det_config, det_ckpt, pose_config, pose_ckpt, device)
>   File "/Users/jaydip/Documents/BCS/ML/MusePose/pose/script/wholebody.py", line 51, in __init__
>     self.detector = init_detector(det_config, det_ckpt, device=device)
> NameError: name 'init_detector' is not defined
> ```
> 
> ### Screnshot###
> ![Screenshot 2024-06-19 at 2 48 33 PM](https://private-user-images.githubusercontent.com/61532589/341013577-87b81dc3-6a4f-4357-9a74-69f1144f66bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NzE5NzgsIm5iZiI6MTcyMTg3MTY3OCwicGF0aCI6Ii82MTUzMjU4OS8zNDEwMTM1NzctODdiODFkYzMtNmE0Zi00MzU3LTlhNzQtNjlmMTE0NGY2NmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAxNDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMDNjYWQ2ODRkOTg3YTBlMmIxZTQyYjQ0NDVhMzc3NDM3NTljNTVhYmI1YzA0ZjQ1MjVlYmJlYmU0MWYxNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9mcrUbJfzxb8sZTvD4lOLk_1I37mW3RzK7E-X0KtXDE)
> 
> I would appreciate any guidance on resolving these issues. Thank you!

I added from mmdet.apis import init_detector to the dwpose.py file, and the issue was resolved!
